name: main

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  screenshots:
    uses: canonical/ubuntu-desktop-installer-screenshots/.github/workflows/ci.yaml@main
    with:
      branch: main
      flutter-version: '3.10.x'
